language: java

addons:
  sonarcloud:
    organization: "krishnawisely"
    token:
      secure: 9f9bce244e86fc71b5e69232acc5352295fa959e
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'   

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=krishnawisely_charity-user-ms
notifications:
  slack: javafullstackgroup:cU6yGmSyVRshhITnnXELpBug
  

  
  
