spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.charityapp.in:3306/charityapp_user_db
    username: prod_user
    password: prod_user
    
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.charityapp.in:3306/charityapp_user_db
    username: prod_user
    password: prod_user